definition:
  openapi: 3.0.0
  info:
    title: Comic Books
    version: 1.0.0
    description: This is a demo project to set up SwaggerUI
  license:
    name: MIT

  servers:
    - url: http://localhost:4000
      description: 'Development server'
    
apis: ["./routes/*.js"]

paths:
  /books:
    get:
      summary: Returns initial db
      description: This is optional
      responses:
        '200':

      