openapi: 3.0.0

definition: myDef -thiskey needs to be here or the app will crash

info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: 'Development server'
    
apis: ["./routes/*.js"]

paths:
  /books:
    get:
      summary: Returns initial db
      description: This is optional
      responses:
        '200':

      